preload = ~/dotfiles/wallpaper/wallpaper
preload = ~/dotfiles/wallpaper/goat.jpg
#if more than one preload is desired then continue to preload other backgrounds
# .. more preloads
splash = off


wallpaper {
    monitor = eDP-1
	path = ~/dotfiles/wallpaper/wallpaper
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
	path = ~/dotfiles/wallpaper/goat.jpg
    fit_mode = cover
}
