arch = {
packages = [
  "adobe-source-han-sans-tw-fonts",
  "alacritty",
  "android-sdk-platform-tools",
  "android-tools",
  "antimicrox",
  "astyle",
  "audacity",
  "baobab",
  "base",
  "base-devel",
  "bash-language-server",
  "bc",
  "bind",
  "binder_linux-dkms",
  "bluedevil",
  "blueman",
  "bluetui",
  "bridge-utils",
  "brightnessctl",
  "calibre",
  "ccls",
  "cliphist",
  "cmake",
  "cmatrix",
  "cups",
  "ddcutil",
  "devtools",
  "dhcpcd",
  "dialog",
  "dmenu",
  "docker",
  "dos2unix",
  "dua-cli",
  "dunst",
  "dwm",
  "efibootmgr",
  "fcitx5",
  "fcitx5-chinese-addons",
  "fcitx5-configtool",
  "fcitx5-gtk",
  "fcitx5-mcbopomofo-git",
  "ffmpegthumbnailer",
  "firefox",
  "flatpak",
  "fluidsynth",
  "fprintd",
  "freerdp",
  "freeze-bin",
  "fwupd",
  "fzf",
  "gimp",
  "git",
  "gn",
  "gobuster",
  "gperf",
  "gphoto2",
  "graphviz",
  "grub",
  "gst-libav",
  "gst-plugin-pipewire",
  "gst-plugins-bad",
  "gst-plugins-good",
  "gvfs",
  "gvfs-mtp",
  "gvfs-smb",
  "handbrake",
  "hyprland",
  "hyprlock",
  "hyprpaper",
  "hyprpicker",
  "hyprshot",
  "ifplugd",
  "inetutils",
  "inkscape",
  "iperf3",
  "iwd",
  "iwgtk",
  "lf",
  "libchewing",
  "libdvdcss",
  "libqalculate",
  "libxml2-legacy",
  "linux",
  "linux-firmware",
  "linux-headers",
  "lld",
  "localsend",
  "luarocks",
  "lutris",
  "makemkv",
  "mariadb-clients",
  "marktext-bin",
  "meld",
  "mesa-utils",
  "mpv",
  "neofetch",
  "neovim",
  "net-tools",
  "nmap",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "noto-fonts-tc",
  "nsxiv",
  "nwg-look",
  "obs-studio",
  "obsidian",
  "omnissa-horizon-client",
  "onlyoffice-bin",
  "openbsd-netcat",
  "opencc",
  "opencl-amd",
  "opencl-mesa",
  "openconnect",
  "openvpn",
  "overskride",
  "pacman-contrib",
  "pam-fprint-grosshack",
  "pandoc-cli",
  "pass",
  "patchutils",
  "pavucontrol",
  "pd",
  "pdfarranger",
  "perl-file-mimeinfo",
  "perl-yaml-tiny",
  "pinta",
  "pipewire",
  "pipewire-alsa",
  "pipewire-pulse",
  "podman",
  "polkit-kde-agent",
  "postgresql",
  "postgresql-libs",
  "power-profiles-daemon",
  "protontricks",
  "pyright",
  "python38",
  "qbittorrent",
  "qemu-full",
  "qt5-graphicaleffects",
  "qt5-quickcontrols",
  "qt5-quickcontrols2",
  "qt5-wayland",
  "qt5ct",
  "qt6-wayland",
  "rawtherapee",
  "rbenv",
  "rclone",
  "ruby",
  "ruby-build",
  "rust-analyzer",
  "rust-bindgen",
  "scrcpy",
  "sddm",
  "sof-firmware",
  "soundfont-fatboy",
  "steam",
  "stow",
  "syncthing",
  "system-config-printer",
  "tcpdump",
  "texlab",
  "texlive-installer",
  "thunar",
  "thunar-archive-plugin",
  "thunar-media-tags-plugin",
  "thunar-shares-plugin",
  "thunderbird",
  "time",
  "tinymist",
  "tldr",
  "tmux",
  "tofi",
  "traceroute",
  "tree-sitter-cli",
  "ttf-arphic-ukai",
  "ttf-jetbrains-mono-nerd",
  "ttf-monoid-nerd",
  "ttf-ms-win10-auto-zh_tw",
  "ttf-times-new-roman",
  "tumbler",
  "typst",
  "udiskie",
  "unityhub",
  "unzip",
  "usbutils",
  "vesktop",
  "vim",
  "virt-manager",
  "virt-viewer",
  "virtio-win",
  "virtualbox",
  "vscode-css-languageserver",
  "wavemon",
  "waybar-git",
  "waydroid",
  "weylus-git",
  "wget",
  "wine",
  "wineasio",
  "winetricks-git",
  "wireless-regdb",
  "wireless_tools",
  "wireplumber",
  "wireshark-qt",
  "wlvncc-git",
  "wtype",
  "xarchiver",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-hyprland",
  "xdg-desktop-portal-wlr",
  "xf86-video-vesa",
  "xorg-bdftopcf",
  "xorg-docs",
  "xorg-font-util",
  "xorg-fonts-100dpi",
  "xorg-fonts-75dpi",
  "xorg-iceauth",
  "xorg-mkfontscale",
  "xorg-server",
  "xorg-server-devel",
  "xorg-server-xephyr",
  "xorg-server-xnest",
  "xorg-server-xvfb",
  "xorg-sessreg",
  "xorg-smproxy",
  "xorg-x11perf",
  "xorg-xauth",
  "xorg-xbacklight",
  "xorg-xcmsdb",
  "xorg-xcursorgen",
  "xorg-xdpyinfo",
  "xorg-xdriinfo",
  "xorg-xev",
  "xorg-xgamma",
  "xorg-xhost",
  "xorg-xkbevd",
  "xorg-xkbutils",
  "xorg-xkill",
  "xorg-xlsatoms",
  "xorg-xlsclients",
  "xorg-xmodmap",
  "xorg-xpr",
  "xorg-xrdb",
  "xorg-xrefresh",
  "xorg-xset",
  "xorg-xsetroot",
  "xorg-xvinfo",
  "xorg-xwd",
  "xorg-xwininfo",
  "xorg-xwud",
  "xterm",
  "yarn",
  "yay",
  "yt-dlp",
  "zathura",
  "zathura-pdf-mupdf",
  "zerotier-one",
  "zip",
  "zoxide",
  "zsh",
  "zsh-vi-mode",
]
}
flatpak = {
repos = [
  { name = "system:flathub", options = { url = "https://dl.flathub.org/repo/" } },
],
packages=[
{name="system:com.moonlight_stream.Moonlight"}
]
}
npm = {
packages=[
  "bash-language-server",
  "node-gyp",
  "nopt",
  "npm",
  "semver",
  "yarn",
]
}
